--FKS

ALTER TABLE portal_sesmt.SOLICITACAO_MV DROP CONSTRAINT FK_CD_SOLICITACAO;
ALTER TABLE portal_sesmt.PRE_SOL_MV     DROP CONSTRAINT FRK_CD_SOLICITACAO;
ALTER TABLE portal_sesmt.ASSINATURA     DROP CONSTRAINT FK_CD_SOLICITACAO_MV;

--DURABILIDADE

-- CREATE TABLE 

DROP TABLE portal_sesmt.DURABILIDADE;

CREATE TABLE portal_sesmt.DURABILIDADE(
CD_DURABILIDADE     INT NOT NULL,
CD_PRODUTO_MV       INT NOT NULL,
SN_ATIVO            VARCHAR(1),
DIAS                INT NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) not null,
HR_CADASTRO         TIMESTAMP(6) not null,
CD_USUARIO_ULT_ALT  VARCHAR2(20),
HR_ULT_ALT          TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_DURABILIDADE PRIMARY KEY (CD_DURABILIDADE),

--UNIQUE_KEY
CONSTRAINT UK_CD_PRODUTO_MV UNIQUE (CD_PRODUTO_MV)

);

--SEQUENCE  

DROP SEQUENCE portal_sesmt.SEQ_CD_DURABILIDADE;
CREATE SEQUENCE portal_sesmt.SEQ_CD_DURABILIDADE  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

----------------------------------------------

SELECT * FROM portal_sesmt.SOLICITACAO sol;

----------------------------------------------

--SOLICITACAO
DROP TABLE portal_sesmt.SOLICITACAO;

CREATE TABLE portal_sesmt.SOLICITACAO(
CD_SOLICITACAO         INT NOT NULL,
CD_USUARIO_MV          VARCHAR(20),
CD_SETOR_MV            INT NOT NULL,
CD_PRODUTO_MV          INT NOT NULL,
CD_UNI_PRO             INT NOT NULL,
CD_DURABILIDADE        INT NULL,
QUANTIDADE             NUMBER(4) NOT NULL,
DS_JUST                VARCHAR(200),
CD_USUARIO_CADASTRO    VARCHAR(20) NOT NULL,
HR_CADASTRO            TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT     VARCHAR(20),
HR_ULT_ALT             TIMESTAMP,
SN_HISTORICO           VARCHAR(1),
HR_SOLICITACAO_HISTORICO TIMESTAMP,

--PRIMARY_KEY
CONSTRAINT PK_CD_SOLICITACAO PRIMARY KEY (CD_SOLICITACAO)

);

--SEQUENCE 
DROP SEQUENCE portal_sesmt.SEQ_CD_SOLICITACAO;
 
CREATE SEQUENCE portal_sesmt.SEQ_CD_SOLICITACAO  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--LOG_SOLICITACAO
DROP TABLE portal_sesmt.LOG_SOLICITACAO;

CREATE TABLE portal_sesmt.LOG_SOLICITACAO(
CD_LOG_SOLICITACAO     INT NOT NULL,
TP_LOG                 VARCHAR(1) NOT NULL, --E (EXCLUSAO)
CD_USUARIO_LOG         VARCHAR(20) NOT NULL,
HR_ACAO_LOG            TIMESTAMP(6) NOT NULL,
CD_SOLICITACAO         INT NOT NULL,
CD_USUARIO_MV          VARCHAR(20),
CD_SETOR_MV            INT NOT NULL,
CD_PRODUTO_MV          INT NOT NULL,
CD_UNI_PRO             INT NOT NULL,
CD_DURABILIDADE        INT NULL,
QUANTIDADE             NUMBER(4) NOT NULL,
DS_JUST_DUR            VARCHAR(200),
CD_USUARIO_CADASTRO    VARCHAR(20) NOT NULL,
HR_CADASTRO            TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT     VARCHAR(20),
HR_ULT_ALT             TIMESTAMP,
SN_HISTORICO           VARCHAR(1),
HR_SOLICITACAO_HISTORICO TIMESTAMP,

--PRIMARY_KEY
CONSTRAINT PK_CD_LOG_SOLICITACAO PRIMARY KEY (CD_LOG_SOLICITACAO)
);

--SEQUENCE 
DROP SEQUENCE portal_sesmt.SEQ_CD_LOG_SOLICITACAO;
 
CREATE SEQUENCE portal_sesmt.SEQ_CD_LOG_SOLICITACAO  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--SOLICITACAO_MV

DROP TABLE portal_sesmt.SOLICITACAO_MV;  

CREATE TABLE portal_sesmt.SOLICITACAO_MV(
CD_SOLICITACAO_MV                INT NOT NULL,
CD_SOLICITACAO                   INT NOT NULL,
CD_SOLSAI_PRO                    INT NOT NULL,
CD_ITSOLSAI_PRO                  INT NOT NULL,
CD_USUARIO_CADASTRO              VARCHAR(20),
HR_CADASTRO                      TIMESTAMP,
CD_USUARIO_ULT_ALT               VARCHAR2(20),
HR_ULT_ALT                       TIMESTAMP,

CONSTRAINT PK_CD_SOLICITACAO_MV PRIMARY KEY(CD_SOLICITACAO_MV),

CONSTRAINT FK_CD_SOLICITACAO  FOREIGN KEY (CD_SOLICITACAO) REFERENCES SOLICITACAO(CD_SOLICITACAO)

);

DROP SEQUENCE portal_sesmt.SEQ_CD_SOLICITACAO_MV;

CREATE SEQUENCE portal_sesmt.SEQ_CD_SOLICITACAO_MV
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;


--LOG_DURABILIDADE
DROP TABLE portal_sesmt.LOG_DURABILIDADE;

CREATE TABLE portal_sesmt.LOG_DURABILIDADE(
CD_LOG_DURABILIDADE    INT NOT NULL,
TP_LOG                 VARCHAR(1) NOT NULL, --E (EXCLUSAO)
CD_USUARIO_LOG         VARCHAR(20) NOT NULL,
CD_DURABILIDADE        INT NOT NULL,
CD_PRODUTO_MV          INT NOT NULL,
SN_ATIVO               VARCHAR(1),
DIAS                   INT NOT NULL,
CD_USUARIO_CADASTRO    VARCHAR(20) not null,
HR_CADASTRO            TIMESTAMP(6) not null,
CD_USUARIO_ULT_ALT     VARCHAR2(20),
HR_ULT_ALT             TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_LOG_DURABILIDADE PRIMARY KEY (CD_LOG_DURABILIDADE)
);

--SEQUENCE 
DROP SEQUENCE portal_sesmt.SEQ_CD_LOG_DURABILIDADE;
 
CREATE SEQUENCE portal_sesmt.SEQ_CD_LOG_DURABILIDADE  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE portal_sesmt.EDITAR_CA;

CREATE TABLE portal_sesmt.EDITAR_CA(
CD_SOLICITACAO     INT NOT NULL,
MV_CA              INT,
EDITADO_SN         VARCHAR(1),
CD_USUARIO_CADASTRO    VARCHAR(20) not null,
HR_CADASTRO            TIMESTAMP not null,
CD_USUARIO_ULT_ALT     VARCHAR2(20),
HR_ULT_ALT             TIMESTAMP

);

DROP TABLE portal_sesmt.PRE_SOL_MV;

CREATE TABLE portal_sesmt.PRE_SOL_MV(
CD_PRE_SOL_MV          INT NOT NULL,
CD_USUARIO_MV          VARCHAR(20),
CD_SOLICITACAO         INT NOT NULL,
CD_USUARIO_CADASTRO    VARCHAR(20),
HR_CADASTRO            TIMESTAMP,
CD_USUARIO_ULT_ALT     VARCHAR2(20),
HR_ULT_ALT             TIMESTAMP,

CONSTRAINT PK_CD_PRE_SOL_MV PRIMARY KEY(CD_PRE_SOL_MV),

CONSTRAINT FRK_CD_SOLICITACAO FOREIGN KEY (CD_SOLICITACAO) REFERENCES SOLICITACAO(CD_SOLICITACAO),

CONSTRAINT UK_USU_SOL UNIQUE (CD_USUARIO_MV,CD_SOLICITACAO)


);

DROP SEQUENCE portal_sesmt.SEQ_CD_PRE_SOL_MV;

CREATE SEQUENCE portal_sesmt.SEQ_CD_PRE_SOL_MV
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;


DROP TABLE portal_sesmt.ASSINATURA;

CREATE TABLE portal_sesmt.ASSINATURA(
CD_ASSINATURA         INT NOT NULL,
CD_SOLICITACAO_MV     INT NOT NULL,
BLOB_ASS              BLOB,
CD_USUARIO_CADASTRO    VARCHAR(20),
HR_CADASTRO            TIMESTAMP,
CD_USUARIO_ULT_ALT     VARCHAR2(20),
HR_ULT_ALT             TIMESTAMP,

CONSTRAINT PK_CD_ASSINATURA PRIMARY KEY (CD_ASSINATURA)

);

DROP SEQUENCE portal_sesmt.SEQ_CD_ASSINATURA;

CREATE SEQUENCE portal_sesmt.SEQ_CD_ASSINATURA
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;


--COMMIT 
COMMIT
