CREATE USER portal_sesmt IDENTIFIED BY sjc_2000_50_15_bilolao;

GRANT CREATE SESSION TO portal_sesmt;
GRANT CREATE PROCEDURE TO portal_sesmt;
GRANT CREATE TABLE TO portal_sesmt;
GRANT CREATE VIEW TO portal_sesmt;
GRANT UNLIMITED TABLESPACE TO portal_sesmt;
GRANT CREATE SEQUENCE TO portal_sesmt;

GRANT EXECUTE ON dbasgu.FNC_MV2000_HMVPEP TO portal_sesmt;

GRANT SELECT ON dbasgu.USUARIOS TO portal_sesmt;
GRANT SELECT ON dbasgu.PAPEL_USUARIOS TO portal_sesmt;

GRANT SELECT ON dbamv.PRODUTO TO portal_sesmt;
GRANT SELECT ON dbamv.SETOR TO portal_sesmt;
