--NEXTVAL SOLSAI_PRO
--SELECT dbamv.SEQ_SOLSAI_PRO.NEXTVAL AS CD_SOLSAI_PRO FROM DUAL;

SELECT *
FROM portal_sesmt.SOLICITACAO_MV

BEGIN
   portal_sesmt.PRC_ACOES_PRE_SOL('HSSAMPAIO','LDPGOMES',7536094);  
END;


DELETE dbamv.ITSOLSAI_PRO itsp WHERE itsp.CD_SOLSAI_PRO = 7536094;

DELETE dbamv.SOLSAI_PRO sp WHERE sp.CD_SOLSAI_PRO = 7536094;

CREATE OR REPLACE PROCEDURE portal_sesmt.PRC_ACOES_PRE_SOL(var_cd_usuario_acao VARCHAR2, var_cd_usuario VARCHAR2, var_cd_solsai_pro NUMBER)

IS 
BEGIN
    
  --------------------------------
  --1º PASSO - INSERT SOLSAI_PRO--
  --------------------------------

  INSERT INTO dbamv.SOLSAI_PRO
  SELECT
  var_cd_solsai_pro AS CD_SOLSAI_PRO, 
  'S' AS TP_SOLSAI_PRO, 
  (SELECT st.CD_SETOR_MV AS CD_SETOR_MV 
   FROM portal_sesmt.SOLICITACAO st 
   WHERE st.CD_SOLICITACAO = psm.CD_SOLICITACAO) AS CD_SETOR,     
  1 AS CD_ESTOQUE,      
  'P' AS TP_SITUACAO,   
  NULL AS CD_ATENDIMENTO,
  NULL AS CD_PRESTADOR, 
  TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY') AS DT_SOLSAI_PRO,
  NULL AS SN_EMITIDO, 
  NULL AS CD_UNID_INT, 
  TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS HR_SOLSAI_PRO,
  NULL AS CD_PRE_MED, 
  NULL AS CD_ESTOQUE_SOLICITANTE, 
  var_cd_usuario_acao AS CD_USUARIO,
  NULL AS CD_SOLICITACAO_PRODUTO,
  'MAT ' || psm.CD_USUARIO_MV AS DS_OBS, 
  NULL AS CD_TP_SOLICITACAO,
  NULL AS CD_MOT_DEV,
  NULL AS DT_IMPRESSAO, 
  NULL AS CD_AGRUPAMENTO, 
  NULL AS CD_OS, 
  NULL AS CD_DEV_PRE, 
  NULL AS CD_AVISO_CIRURGIA, 
  TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS DT_GRAVACAO, 
  NULL AS CD_TURNO, 
  NULL AS DT_IMPRESSAO_AGRUP,
  NULL AS DT_CONSUMO_INICIAL, 
  NULL AS DT_CONSUMO_FINAL, 
  'N' AS SN_URGENTE, 
  NULL AS CD_FECHAMENTO, 
  NULL AS TP_ORIGEM_SOLICITACAO, 
  NULL AS CD_SOLSAI_PRO_INTEGRA, 
  NULL AS CD_SEQ_INTEGRA, 
  NULL AS DT_INTEGRA, 
  NULL AS CD_PACIENTE_INTEGRA, 
  NULL AS NM_PACIENTE_INTEGRA, 
  NULL AS CD_ENT_PRO, 
  NULL AS CD_MUNICIPIO, 
  NULL AS DS_MUNICIPIO, 
  NULL AS CD_MUNICIPIO_INTEGRA,  
  NULL AS CD_CLINICA, 
  NULL AS DS_CLINICA, 
  NULL AS CD_CLINICA_INTEGRA, 
  NULL AS CD_ATENDIMENTO_INTEGRA, 
  NULL AS SN_CONTROLA_ATEND_DEVOL, 
  NULL AS CD_REQUISICAO, 
  NULL AS CD_MOTIVO_CANC, 
  NULL AS DT_CANCELAMENTO, 
  NULL AS DS_JUSTIFICATIVA_CANCELAMENTO, 
  'N' AS SN_SOLIC_PADRAO, 
  'S' AS SN_ATIVO_SOLIC_PADRAO, 
  NULL AS DS_SOLIC_PADRAO,
  NULL AS CD_EMPRESA_DESTINO,
  NULL AS CD_MOVIMENTACAO_EST_RCBM_PARCI,
  NULL AS TP_STATUS_ROMANEIO,
  NULL AS CD_AVISO_CIRURGIA_PROD_ROUPA
  --SELECT * 
  FROM portal_sesmt.PRE_SOL_MV psm
  INNER JOIN dbasgu.USUARIOS usu
    ON usu.CD_USUARIO = psm.CD_USUARIO_MV
  WHERE psm.CD_USUARIO_MV = var_cd_usuario
  AND psm.CD_SOLICITACAO IN (SELECT MAX(aux.CD_SOLICITACAO) AS CD_SOLICITACAO
                             FROM portal_sesmt.PRE_SOL_MV aux
                             WHERE aux.CD_USUARIO_MV = var_cd_usuario);


  ----------------------------------
  --2º PASSO - INSERT ITSOLSAI_PRO--
  ----------------------------------


  INSERT INTO dbamv.ITSOLSAI_PRO
  SELECT 
  dbamv.SEQ_ITSOLSAI_PRO.NEXTVAL AS CD_ITSOLSAI_PRO,
  var_cd_solsai_pro AS CD_SOLSAI_PRO,
  sol.CD_PRODUTO_MV AS CD_PRODUTO, 
  sol.CD_UNI_PRO AS CD_UNI_PRO, 
  sol.QUANTIDADE AS QT_SOLICITADO,
  NULL AS CD_TIP_PRESC, 
  NULL AS CD_TIP_FRE, 
  NULL AS SN_ATENDIDO, 
  NULL AS CD_UNIDADE, 
  NULL AS CD_KIT_ESTOQUE,
  NULL AS CD_TIP_PRESC_KIT, 
  NULL AS CD_LOTE,
  NULL AS DT_VALIDADE, 
  NULL AS QT_PRESCRITA,
  NULL AS NR_DIAS, 
  NULL AS TP_USO_PRODUTO, 
  NULL AS CD_PRODUTO_KIT, 
  NULL AS CD_FORMULA_KIT, 
  NULL AS QT_KIT, 
  NULL AS CD_MOT_DEV, 
  'S'  AS SN_FATURA, 
  NULL AS CD_ITPRE_MED, 
  0 AS QT_ATENDIDA, 
  NULL AS DS_NPADRONIZADO, 
  NULL AS CD_ITDEV_PRE, 
  NULL AS DS_OBS_ITPRE_MED, 
  'N'  AS SN_CONF_DETERM_USU,
  TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS DT_GRAVACAO, 
  NULL AS DSP_CODIGO_DE_BARRAS, 
  NULL AS DS_ALERTA_AUTOMATICO, 
  NULL AS CD_ITSOLSAI_PRO_INTEGRA, 
  NULL AS CD_SEQ_INTEGRA, 
  NULL AS DT_INTEGRA, 
  NULL AS CD_MOTIVO_DIVERG_ATEND, 
  NULL AS SN_IMPRIME_ETQ_DOSE, 
  NULL AS DT_ESTORNO_FFCV, 
  NULL AS CD_ITENT_PRO, 
  'N'  AS SN_COMPONENTE
  FROM portal_sesmt.PRE_SOL_MV psm
  INNER JOIN portal_sesmt.SOLICITACAO sol
     ON sol.CD_SOLICITACAO = psm.CD_SOLICITACAO
  WHERE psm.CD_USUARIO_MV = var_cd_usuario;
  
  ----------------------------------------------------------
  --3º PASSO - ALIMENTA A TABELA DE VINCULO SOLICITACAO_MV--
  ----------------------------------------------------------
  
  INSERT INTO portal_sesmt.SOLICITACAO_MV smv
  SELECT
  portal_SESMT.SEQ_CD_SOLICITACAO_MV AS CD_SOLICITACAO_MV,
  AS CD_SOLICITACAO,
  itsp.CD_SOLSAI_PRO AS CD_SOLSAI_PRO,
  itsp.CD_ITSOLSAI_PRO AS CD_ITSOLSAI_PRO,
  var_cd_usuario_acao AS CD_USUARIO_CADASTRO,
  SYSDATE AS HR_CADASTRO,
  NULL AS CD_USUARIO_ULT_ALT,
  NULL AS HR_ULT_ALT  
  FROM dbamv.SOLSAI_PRO itsp
  WHERE itsp.CD_SOLSAI_PRO = var_cd_solsai_pro;
    
   
  ------------------------------------------
  --4º PASSO - EXCLUIR DADOS DA PRE_SOL_MV--
  ------------------------------------------
  
  DELETE FROM portal_sesmt.PRE_SOL_MV psm
  WHERE psm.CD_USUARIO_MV = var_cd_usuario;
    
  --COMMIT
  COMMIT;

END;
