---------------------
--ESTRUTURA----------
---------------------

---------------------
--DELETE-------------
---------------------

DELETE FROM portal_sesmt.PRE_SOL_MV psm
--WHERE psm.CD_USUARIO_MV = UPPER('LDPGOMES')
--------------------------------------

---------------------
--INSERT-------------
---------------------

INSERT INTO portal_sesmt.PRE_SOL_MV

SELECT 
portal_sesmt.SEQ_CD_PRE_SOL_MV.NEXTVAL AS CD_PRE_SOL_MV,
'LDPGOMES'        AS CD_USUARIO_MV,
1                 AS CD_SOLICITACAO,
'HSSAMPAIO'       AS CD_USUARIO_CADASTRO,
SYSDATE           AS HR_CADASTRO,
NULL              AS CD_USUARIO_ULT_ALT,
SYSDATE           AS HR_ULT_ALT

FROM DUAL;


---------------------
--PROCEDURE----------
---------------------

--1 ETL SOL SAI PRO
SELECT
NULL AS CD_SOLSAI_PRO,
'S' AS TP_SOLSAI_PRO,
NULL AS CD_SETOR, 
1 AS CD_ESTOQUE,
'P' AS TP_SITUACAO,
NULL AS CD_ATENDIMENTO,
NULL AS CD_PRESTADOR,
TO_DATE(SYSDATE,'DD/MM/YYYY') AS DT_SOLSAI_PRO,
NULL AS SN_EMITIDO,
NULL AS CD_UNID_INT,
TO_DATE(SYSDATE,'DD/MM/YYYY HH24:MI:SS') AS HR_SOLSAI_PRO,
NULL AS CD_PRE_MED,
NULL AS CD_ESTOQUE_SOLICITANTE,
psm.CD_USUARIO_MV AS CD_USUARIO,
NULL AS CD_SOLICITACAO_PRODUTO,
NULL AS DS_OBS,
NULL AS CD_TP_SOLICITACAO,
NULL AS CD_MOT_DEV,
NULL AS DT_IMPRESSAO,
NULL AS CD_AGRUPAMENTO,
NULL AS CD_OS,
NULL AS CD_DEV_PRE,
NULL AS CD_AVISO_CIRURGIA,
NULL AS DT_GRAVACAO,
NULL AS CD_TURNO,
NULL AS DT_IMPRESSAO_AGRUP,
NULL AS DT_CONSUMO_INICIAL,
NULL AS DT_CONSUMO_FINAL,
NULL AS SN_URGENTE,
NULL AS CD_FECHAMENTO,
NULL AS TP_ORIGEM_SOLICITACAO,
NULL AS CD_SOLSAI_PRO_INTEGRA,
NULL AS CD_SEQ_INTEGRA,
NULL AS DT_INTEGRA,
NULL AS CD_PACIENTE_INTEGRA,
NULL AS NM_PACIENTE_INTEGRA,
NULL AS CD_ENT_PRO,
NULL AS CD_MUNICIPIO,
NULL AS DS_MUNICIPIO,
NULL AS CD_MUNICIPIO_INTEGRA,
NULL AS CD_CLINICA,
NULL AS DS_CLINICA,
NULL AS CD_CLINICA_INTEGRA,
NULL AS CD_ATENDIMENTO_INTEGRA,
NULL AS SN_CONTROLA_ATEND_DEVOL,
NULL AS CD_REQUISICAO,
NULL AS CD_MOTIVO_CANC,
NULL AS DT_CANCELAMENTO,
NULL AS DS_JUSTIFICATIVA_CANCELAMENTO,
NULL AS SN_SOLIC_PADRAO,
NULL AS SN_ATIVO_SOLIC_PADRAO,
NULL AS DS_SOLIC_PADRAO,
NULL AS CD_EMPRESA_DESTINO,
NULL AS CD_MOVIMENTACAO_EST_RCBM_PARCI,
NULL AS TP_STATUS_ROMANEIO,
NULL AS CD_AVISO_CIRURGIA_PROD_ROUPA
--SELECT * 
FROM portal_sesmt.PRE_SOL_MV psm
WHERE psm.CD_USUARIO_MV = 'LDPGOMES'
