
--1 NEXTVAL SOL SAI PRO
--SELECT dbamv.SEQ_SOLSAI_PRO.NEXTVAL AS CD_SOLSAI_PRO FROM DUAL;

7035185

--2 ETL SOL SAI PRO

SELECT * FROM dbamv.SOLSAI_PRO ORDER BY 1 DESC

INSERT INTO dbamv.SOLSAI_PRO
SELECT
7035185 AS CD_SOLSAI_PRO, --ok
'S' AS TP_SOLSAI_PRO, --ok
282 AS CD_SETOR,     
1 AS CD_ESTOQUE,      --ok
'P' AS TP_SITUACAO,   --ok
NULL AS CD_ATENDIMENTO,--ok
NULL AS CD_PRESTADOR, --ok
TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY') AS DT_SOLSAI_PRO,--ok
NULL AS SN_EMITIDO, --ok
NULL AS CD_UNID_INT, --ok
TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS HR_SOLSAI_PRO,--ok
NULL AS CD_PRE_MED, --ok
NULL AS CD_ESTOQUE_SOLICITANTE, --ok
'HSSAMPAIO' AS CD_USUARIO,--ok
NULL AS CD_SOLICITACAO_PRODUTO,--ok
'MAT ' || 'HSSAMPAIO' AS DS_OBS, --ok
NULL AS CD_TP_SOLICITACAO,--ok
NULL AS CD_MOT_DEV,--ok
NULL AS DT_IMPRESSAO, --ok
NULL AS CD_AGRUPAMENTO, --ok
NULL AS CD_OS, --ok
NULL AS CD_DEV_PRE, --ok
NULL AS CD_AVISO_CIRURGIA, --ok
TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS DT_GRAVACAO, --ok
NULL AS CD_TURNO, --ok
NULL AS DT_IMPRESSAO_AGRUP,--ok
NULL AS DT_CONSUMO_INICIAL, --ok
NULL AS DT_CONSUMO_FINAL, --ok
'N' AS SN_URGENTE, --ok
NULL AS CD_FECHAMENTO, --ok
NULL AS TP_ORIGEM_SOLICITACAO, --ok
NULL AS CD_SOLSAI_PRO_INTEGRA, --ok
NULL AS CD_SEQ_INTEGRA, --ok
NULL AS DT_INTEGRA, --ok
NULL AS CD_PACIENTE_INTEGRA, --ok
NULL AS NM_PACIENTE_INTEGRA, --ok
NULL AS CD_ENT_PRO, --ok
NULL AS CD_MUNICIPIO, --ok
NULL AS DS_MUNICIPIO, --ok
NULL AS CD_MUNICIPIO_INTEGRA,  --ok
NULL AS CD_CLINICA, --ok
NULL AS DS_CLINICA, --ok
NULL AS CD_CLINICA_INTEGRA, --ok
NULL AS CD_ATENDIMENTO_INTEGRA, --ok
NULL AS SN_CONTROLA_ATEND_DEVOL, --ok
NULL AS CD_REQUISICAO, --ok
NULL AS CD_MOTIVO_CANC, --ok
NULL AS DT_CANCELAMENTO, --ok
NULL AS DS_JUSTIFICATIVA_CANCELAMENTO, --ok
'N' AS SN_SOLIC_PADRAO, --ok
'S' AS SN_ATIVO_SOLIC_PADRAO, --ok
NULL AS DS_SOLIC_PADRAO,--ok
NULL AS CD_EMPRESA_DESTINO,--ok
NULL AS CD_MOVIMENTACAO_EST_RCBM_PARCI,--ok
NULL AS TP_STATUS_ROMANEIO,--ok
NULL AS CD_AVISO_CIRURGIA_PROD_ROUPA--ok
--SELECT * 
FROM DUAL


